In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

In [3]:
df = pd.read_csv("data.csv")

In [4]:
df.head()

Your Roll Number Your Section  CLA  Mid  Lab Internal  Therory total  \
0       19110010001        CSE A    7   12            42             38   
1       19110010002        CSE A    6   10            35             32   
2       19110010003        CSE A    6   13            38             38   
3       19110010004        CSE A    7   11            36             36   
4       19110010005        CSE D    6    9            49             30   

   Attendance Performance  
0   90 to 95%        Good  
1  96 to 100%     Average  
2   90 to 95%        Good  
3  96 to 100%        Good  
4  96 to 100%        Poor

In [5]:
X = df.iloc[:,2 :-2].values
y = df.iloc[:, 7].values

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [9]:
y_pred  =  classifier.predict(X_test)

In [10]:
 y_pred  

array(['Good', 'Very Good', 'Very Good', 'Very Good', 'Excellent', 'Poor',
       'Average', 'Good', 'Very Good', 'Good', 'Average', 'Excellent',
       'Very Good', 'Good', 'Very Good', 'Poor', 'Very Good', 'Good',
       'Excellent', 'Good', 'Good', 'Excellent', 'Good', 'Very Good',
       'Good', 'Very Good', 'Very Good', 'Very Good', 'Excellent', 'Good',
       'Good', 'Poor', 'Excellent', 'Average', 'Excellent', 'Excellent',
       'Good', 'Poor', 'Good', 'Good'], dtype='<U9')

In [11]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test,y_pred)

In [12]:
print("Accuracy score: ",ac)

Accuracy score:  1.0


In [14]:
print("Confusion Matrix :\n", cm)

Confusion Matrix :
 [[ 3  0  0  0  0]
 [ 0  8  0  0  0]
 [ 0  0 14  0  0]
 [ 0  0  0  4  0]
 [ 0  0  0  0 11]]
